title: Sense HAT Minecraft Map
hero_image: images/banner.png
description: 'Use the Sense HAT to create a map of the world around your player in
Minecraft: Pi Edition'
original_url: https://raspberrypi.org/learning/sense-hat-minecraft-map
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 3, design-0, programming-3, phys-comp-1, manufacture-0, community-0
interests: games
technologies: raspberry-pi, electronic-components, python, sense-hat
site_areas: projects
hardware: raspberry-pi, electronic-components, sense-hat
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Display a colour
- title: What am I standing on?
- title: Display the block colour
- title: Set a single LED
- title: Create a mini map
- title: Reduce the lag with caching
- title: Create the map
- title: "Challenge: Improve your map"